### ISSUE TITLE
StackOverflowError in huawei  P8 Lite android 5.0

### ISSUE THREAD

**Issue by onirban27** [Nikoloutsos/KLoadingSpin#6]
11-19 03:54:05.405: E/AndroidRuntime(22149): java.lang.StackOverflowError: stack size 8MB
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.view.View.skipInvalidate(View.java:11484)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.view.View.invalidateInternal(View.java:11570)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.view.View.invalidate(View.java:11560)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.view.View.invalidate(View.java:11544)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin$a.onAnimationUpdate()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:959)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:969)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin.a()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin$a.onAnimationUpdate()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:959)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:969)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin.a()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin$a.onAnimationUpdate()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:959)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:969)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin.a()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin$a.onAnimationUpdate()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animat
ion.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:959)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:969)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin.a()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin$a.onAnimationUpdate()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:959)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:969)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin.a()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin$a.onAnimationUpdate()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:959)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:969)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin.a()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at com.example.kloadingspin.KLoadingSpin$a.onAnimationUpdate()
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:546)
11-19 03:54:05.405: E/AndroidRuntime(22149): 	at android.animation.ValueAnimator.start(ValueAnimator.java:

**Comment by Nikoloutsos** [comment]
Hi, can you show some code you use in order to show the loading spinner?

**Comment by onirban27** [comment]
kloadingSpinner.changeSpinnerDimension(50, 10);
        kloadingSpinner.startAnimation();
        kloadingSpinner.setIsVisible(true);

then calling a webview for linkedin authentication. but it crashes right after spinner initiates.

**Comment by Nikoloutsos** [comment]
I will take a look at it tonight and I'll let you know. It seems like for some reason we have an infinite recursion.

**Comment by Nikoloutsos** [comment]
Sorry for not replying to this issue for so long but I have a lot of work.
